import formValidate from "@/utils/formValidate";

export default () => [
  {
    tabCode: "basicInfo",
    tabName: "基本信息",
    tabContent: [
      { prop: "productCategoryIdText", label: "物料分类", value: "", type: 'custom', customComponent: "ComSelect-list", itemRules: [{ required: true, message: "请选择物料分类", trigger: "no" }] },
      { prop: "code", label: "产品编码", value: "", type: 'input', itemRules: [{ required: true, trigger: "blur" }, { validator: formValidate('enCode'), trigger: 'blur' }], itemReadOnly: true },
      { prop: "name", label: "产品名称", value: "", type: 'input', maxlength: 100, itemRules: [{ required: true, message: "请输入产品名称", trigger: "blur" }] },
      { prop: "drawingNo", label: "图号", value: "", type: 'input', maxlength: 200, itemRules: [{ required: true, trigger: "blur" }, { validator: formValidate('noSpace'), trigger: 'blur' }], itemReadOnly: true },
      { prop: "productType", label: "产品类别", value: "", type: "select", options: [/* 从数据字典获取 */], itemDisabled: false },
      { prop: "spec", label: "规格型号", value: "", type: 'input', maxlength: 50 },
      { prop: "mainUnit", label: "主单位", value: "", type: 'input', itemRules: [{ required: true, trigger: "blur" }] },
      { prop: "deputyUnit", label: "副单位", value: "", type: 'input', itemRules: [{ required: true, trigger: "blur" }] },
      { prop: "ratio", label: "转换系数", value: "", type: 'input', itemRules: [{ required: true, trigger: "blur" }, { validator: formValidate({ type: 'decimal', params: [10, 6] }), trigger: 'blur' }, { validator: formValidate('positiveNumber'), trigger: "blur" }] },
      { prop: "calculationDirection", label: "计算方向", value: "", type: "select", options: [{ label: "乘", value: "multiplication" }, { label: "除", value: "division" }], itemRules: [{ required: true, trigger: "change" }] },
      { prop: "brand", label: "品牌", value: "", type: 'input', maxlength: 200 },
      { prop: "extent", label: "长", value: "", type: 'input', itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(mm)' } },
      { prop: "width", label: "宽", value: "", type: 'input', itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(mm)' } },
      { prop: "height", label: "高", value: "", type: 'input', itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(mm)' } },
      { prop: "unitVolume", label: "单位体积", value: "", type: 'input', placeholder: ' ', itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'change' }], itemDisabled: true, itemSlot: { position: 'append', content: '(cm³)' } },
      { prop: "grossWeightCoefficient", label: "理论重量(kg/m)", value: "", type: 'input', itemRules: [{ validator: formValidate('positiveNumber'), trigger: 'blur' }, { validator: formValidate({ type: 'decimal', params: [20, 6] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(kg/m)' } },
      { prop: "netWeight", label: "净重", value: "", type: 'input', itemRules: [{ validator: formValidate({ type: 'decimal', params: [20, 6] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(kg)' } },
      { prop: "grossWeight", label: "毛重", value: "", type: 'input', itemRules: [{ validator: formValidate({ type: 'decimal', params: [20, 6] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(kg)' } },
      { prop: "expendableWeight", label: "耗重", value: "", type: 'input', itemRules: [{ validator: formValidate({ type: 'decimal', params: [20, 6] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(kg)' } },
      { prop: "packagingMaterialsText", label: "包材", value: "", type: 'custom', customComponent: "ComSelect-page" },
      { prop: "packing", label: "装箱数", value: "", type: "input", maxlength: 9, itemRules: [{ validator: formValidate('bigInt'), trigger: 'blur' }] },
      { prop: "barCode", label: "条形码", value: "", type: 'input', maxlength: 50 },
      { prop: "inspectionMethod", label: "检验方式", value: "", type: "select", options: [{ label: "免检", value: "exempt" }, { label: "抽检", value: "spot_check" }, { label: "全检", value: "all" }], itemDisabled: true },
      { prop: "spotCheckRatio", label: "抽检比例", value: "", type: "input", itemDisabled: true, itemSlot: { position: 'append', content: '(%)' }, render: false },
      { prop: "deductionFee", label: "扣压费", value: "", type: 'input', itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }] },
      { prop: "materialQualityText", label: "材质", value: "", type: 'custom', customComponent: "ComSelect-list" },
      { prop: "density", label: "密度", value: "", type: 'input', itemRules: [{ validator: formValidate({ type: 'decimal', params: [20, 6] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(kg/m³)' } },
      { prop: "acrossFlats", label: "对边", value: "", type: 'input', itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }] },
      { prop: "insideDiameter", label: "内径", value: "", type: 'input', itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(mm)' } },
      { prop: "externalDiameter", label: "外径", value: "", type: 'input', itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(mm)' } },
      { prop: "wallThickness", label: "壁厚", value: "", type: 'input', itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }] },
      { prop: "abc", label: "abc分类", value: "", type: "select", options: [{ label: "特别重要的库存(A类)", value: "A" }, { label: "一般重要的库存(B类)", value: "B" }, { label: "不重要的库存(C类)", value: "C" }] },
      { prop: "productSource", label: "产品来源", value: "", type: "select", options: [{ label: "自制", value: "produce" }, { label: "采购", value: "purchase" }, { label: "外协", value: "out" }], itemRules: [{ required: true, trigger: "change" }], itemReadOnly: true },
      { prop: "productStatus", label: "产品状态", value: "enable", type: "select", options: [{ label: "启用", value: "enable" }, { label: "禁用", value: "disabled" }], itemRules: [{ required: true, trigger: "change" }] },
      // { prop: "approvalStatus", label: "审批状态", value: "", type: "select", options: [{ label: "审批中", value: "in_approval" }, { label: "审批通过", value: "approved" }, { label: "审批拒绝", value: "review_failed" }] },
      // { prop: "reasonRejection", label: "驳回理由", value: "", type: 'textarea', sm: 24 },
      // { prop: "approvalCompletionDate", label: "审批完成时间", value: "", type: 'date' },
      // { prop: "documentStatus", label: "单据状态", value: "", type: "select", options: [{ label: "草稿", value: "draft" }, { label: "提交", value: "submit" }] },
      // { prop: "submitDate", label: "提交时间", value: "", type: 'date' },
      { prop: "version", label: "版本", value: "", type: "input", itemReadOnly: true },
      { prop: "standardPrice", label: "标准单价", value: "0", type: "input", itemSlot: { position: 'append', content: '(kg/元)' } },
      { prop: "remark", label: "备注", value: "", type: 'textarea', sm: 24 },
    ],
  },
  {
    tabCode: "specialAttribute",
    tabName: "特殊属性",
    tabContent: [
      { prop: "minInventory", label: "最小库存", value: "", type: "input", itemReadOnly: true },
      { prop: "maxInventory", label: "最大库存", value: "", type: "input", itemReadOnly: true },
      { prop: "safeInventory", label: "安全库存", value: "", type: "input", itemReadOnly: true },
      // { prop: "taxRate", label: "税率", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }] },
      // { prop: "purchasePrice", label: "采购牌价(含税)", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }], readOndy: true },
      // { prop: "salePrice", label: "销售牌价(含税)", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }], readOndy: true },
      // { prop: "costPrice", label: "成本价格(含税)", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [20, 8] }), trigger: 'blur' }], readOndy: true },
      // { prop: "excludingTaxCostPrice", label: "成本价格（不含税）", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [20, 8] }), trigger: 'blur' }], readOndy: true },
      // { prop: "provisionalEstimate", label: "暂估价（含税）", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }] },
      // { prop: "purchasingUnit", label: "采购单位", value: "", type: "input" },
      // { prop: "procurementConversionCoefficient", label: "采购单位转换系数", value: "1", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 6] }), trigger: 'blur' }, { validator: formValidate('positiveNumber'), trigger: "blur" }] },
      // { prop: "batchFlag", label: "是否采用批次管理", value: "", type: "select", options: [{ label: "采用", value: true }, { label: "不采用", value: false }] },
      // { prop: "outboundMethod", label: "出库方式", value: "no_control", type: "select", options: [{ label: "按批号大小顺序", value: "size_order" }, { label: "按批次先入先出", value: "first_in_first_out" }, { label: "按保质期", value: "quality_guarantee_period" }, { label: "不做控制", value: "no_control" }] },
      // { prop: "procurementLeadTimeDay", label: "采购提前期", value: "", type: "input", itemRules: [{ validator: formValidate('bigInt'), trigger: 'blur' }], itemSlot: { position: 'append', content: '(天)' } },
      // { prop: "procurementReturnFlag", label: "是否允许采购退货", value: "", type: "select", options: [{ label: "允许", value: true }, { label: "不允许", value: false }] },
      // { prop: "overchargeRatio", label: "允许超收比例", value: "1", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(%)' } },
      // { prop: "underpaymentRatio", label: "允许欠收比例", value: "1", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(%)' } },
      // { prop: "inspectFlag", label: "收货是否检验", value: "", type: "select", options: [{ label: "是", value: true }, { label: "否", value: false }] },
      { prop: "dailyConsumption", label: "日消耗量", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }] },
      { prop: "steelWireJointText", label: "钢丝接头", value: "", type: 'custom', customComponent: "ComSelect-page" },
      { prop: "copperTubeText", label: "铜管", value: "", type: 'custom', customComponent: "ComSelect-page" },
      { prop: "wireText", label: "钢丝", value: "", type: 'custom', customComponent: "ComSelect-page" },
    ]
  },
  {
    tabCode: "rubberTube",
    tabName: "胶管属性",
    tabContent: [
      { prop: "layerCount", label: "胶管层数", value: undefined, type: "select", options: [{ label: "1-2层", value: "1-2" }, { label: "3-4层", value: "3-4" }, { label: "6层", value: "6" }, { label: "水管", value: "water_pipes" }, { label: "铁佛龙管", value: "iron_buddha_dragon" }, { label: "测压表线", value: "pressure_gauge" }, { label: "黄油管", value: "butter_tube" }, { label: "其他", value: "other" }], itemRules: [] },
      { prop: "hoseNo", label: "胶管标号", value: undefined, type: "input", itemRules: [] },
      { prop: "compressionElongation", label: "扣压伸长量", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(mm)' } },
      { prop: "workingPressure", label: "工作压力", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(Mpa)' } },
      { prop: "testPressure", label: "测试压力", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(Mpa)' } },
      { prop: "temperatureRange", label: "工作温度范围", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal2', params: [10, 2] }), trigger: 'blur' }], maxlength: 20, itemSlot: { position: 'append', content: '(℃)' } },
      { prop: "minBendRadius", label: "最小弯曲 R半径", value: "", type: "input", maxlength: 20, itemSlot: { position: 'append', content: '(mm)' } },
      { prop: "pipeClampText", label: "管夹", value: "", type: "custom", customComponent: "ComSelect-page" },
      { prop: "coreHoleDeformation", label: "芯孔变型量", value: "", type: "input", placeholder: "示例值：1.3-2.4", itemSlot: { position: 'append', content: '(mm)' } },
      { prop: "hoseInternalDiameter", label: "胶管内径", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(mm)' } },
      { prop: "hoseOd", label: "胶管外径", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(mm)' } },
      { prop: "outerAdhesiveLayer", label: "外胶层", value: "", type: "input", maxlength: 100 },
      { prop: "applicationStandards", label: "应用标准", value: "", type: "input", maxlength: 100 },
      { prop: "whiteXiumingNylonSheathText", label: "白色透明尼龙护套PNS", value: "", type: "custom", customComponent: "ComSelect-page" },
      { prop: "stainlessSteelSheathText", label: "不锈钢护套WS", value: "", type: "custom", customComponent: "ComSelect-page" },
      { prop: "spiralNylonSheathText", label: "螺旋尼龙护套RNL", value: "", type: "custom", customComponent: "ComSelect-page" },
      { prop: "protectiveSpringText", label: "保护簧Rs/Rm", value: "", type: "custom", customComponent: "ComSelect-page" },
      { prop: "fireproofSleeveText", label: "防火套FJ", value: "", type: "custom", customComponent: "ComSelect-page" },
      { prop: "zrtSheathText", label: "ZRT护套", value: "", type: "custom", customComponent: "ComSelect-page" },
      { prop: "baojiapg", label: "保甲 PG", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }] },
      { prop: "baojia1Text", label: "保甲1（卡箍固定）", value: "", type: "custom", customComponent: "ComSelect-page" },
      { prop: "baojia2Text", label: "保甲2（铝套扣压）", value: "", type: "custom", customComponent: "ComSelect-page" },
      { prop: "baojia3Text", label: "保甲3（C环扣压）", value: "", type: "custom", customComponent: "ComSelect-page" },
      { prop: "baojia4Text", label: "保甲4", value: "", type: "custom", customComponent: "ComSelect-page" },
      { prop: "clampText", label: "卡箍", value: "", type: "custom", customComponent: "ComSelect-page" },
      // { prop: "clamp1Text", label: "卡箍1", value: "", type: "custom", customComponent: "ComSelect-page" },
      // { prop: "clamp2Text", label: "卡箍2", value: "", type: "custom", customComponent: "ComSelect-page" },
      // { prop: "clamp3Text", label: "卡箍3", value: "", type: "custom", customComponent: "ComSelect-page" },
      // { prop: "clamp4Text", label: "卡箍4", value: "", type: "custom", customComponent: "ComSelect-page" },
    ]
  }
]