import formValidate from "@/utils/formValidate";

export default () => [
  {
    tabCode: "basicInfo",
    tabName: "基本信息",
    tabContent: [
      { prop: "productCategoryIdText", label: "物料分类", value: "", type: 'custom', customComponent: "ComSelect-list", itemRules: [{ required: true, message: "请选择物料分类", trigger: "no" }] },
      { prop: "code", label: "产品编码", value: "", type: 'input', itemRules: [{ required: true, trigger: "blur" }, { validator: formValidate('enCode'), trigger: 'blur' }], itemReadOnly: true },
      { prop: "name", label: "产品名称", value: "", type: 'input', maxlength: 100, itemRules: [{ required: true, message: "请输入产品名称", trigger: "blur" }] },
      { prop: "drawingNo", label: "图号", value: "", type: 'input', maxlength: 200, itemRules: [{ required: true, trigger: "blur" }, { validator: formValidate('noSpace'), trigger: 'blur' }], itemReadOnly: true },
      { prop: "productType", label: "产品类别", value: "", type: "select", options: [/* 从数据字典获取 */], itemDisabled: false },
      { prop: "spec", label: "规格型号", value: "", type: 'input', maxlength: 50 },
      { prop: "mainUnit", label: "主单位", value: "", type: 'input', itemRules: [{ required: true, trigger: "blur" }] },
      { prop: "deputyUnit", label: "副单位", value: "", type: 'input', itemRules: [{ required: true, trigger: "blur" }] },
      { prop: "ratio", label: "转换系数", value: "", type: 'input', itemRules: [{ required: true, trigger: "blur" }, { validator: formValidate({ type: 'decimal', params: [10, 6] }), trigger: 'blur' }, { validator: formValidate('positiveNumber'), trigger: "blur" }] },
      { prop: "calculationDirection", label: "计算方向", value: "", type: "select", options: [{ label: "乘", value: "multiplication" }, { label: "除", value: "division" }], itemRules: [{ required: true, trigger: "change" }] },
      { prop: "extent", label: "长", value: "", type: 'input', itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(mm)' } },
      { prop: "width", label: "宽", value: "", type: 'input', itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(mm)' } },
      { prop: "height", label: "高", value: "", type: 'input', itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(mm)' } },
      { prop: "unitVolume", label: "单位体积", value: "0", type: 'input', itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'change' }], itemDisabled: true, itemSlot: { position: 'append', content: '(cm³)' } },
      { prop: "netWeight", label: "净重", value: "", type: 'input', itemRules: [{ validator: formValidate({ type: 'decimal', params: [20, 6] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(kg)' } },
      { prop: "grossWeight", label: "毛重", value: "", type: 'input', itemRules: [{ validator: formValidate({ type: 'decimal', params: [20, 6] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(kg)' } },
      { prop: "expendableWeight", label: "耗重", value: "", type: 'input', itemRules: [{ validator: formValidate({ type: 'decimal', params: [20, 6] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(kg)' } },
      { prop: "barCode", label: "条形码", value: "", type: 'input', maxlength: 50 },
      { prop: "materialQualityText", label: "材质", value: "", type: 'custom', customComponent: "ComSelect-list" },
      { prop: "inspectionMethod", label: "检验方式", value: "", type: "select", options: [{ label: "免检", value: "exempt" }, { label: "抽检", value: "spot_check" }, { label: "全检", value: "all" }], itemDisabled: true },
      { prop: "spotCheckRatio", label: "抽检比例", value: "", type: "input", itemDisabled: true, itemSlot: { position: 'append', content: '(%)' }, render: false },
      { prop: "blankingSpecifications", label: "下料规格", value: "", type: "input", maxlength: "50" },
      { prop: "blankingLength", label: "下料长", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(mm)' } },
      { prop: "workshopId", label: "生产车间", value: "", type: "input", maxlength: "64" },
      { prop: "blankingLengthTolerance", label: "下料长度公差", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }] },
      { prop: "blankingWeightTolerance", label: "下料重量公差", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }] },
      { prop: "shoulderLength", label: "夹肩长", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(mm)' } },
      { prop: "storageLocation", label: "存储地", value: "", type: "input", maxlength: "50" },
      { prop: "packagingMaterialsText", label: "包材", value: "", type: 'custom', customComponent: "ComSelect-page" },
      { prop: "packing", label: "装箱数", value: "", type: "input", maxlength: 9, itemRules: [{ validator: formValidate('bigInt'), trigger: 'blur' }] },
      { prop: "economize", label: "省管量", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }] },
      { prop: "abc", label: "abc分类", value: "", type: "select", options: [{ label: "特别重要的库存(A类)", value: "A" }, { label: "一般重要的库存(B类)", value: "B" }, { label: "不重要的库存(C类)", value: "C" }] },
      { prop: "productSource", label: "产品来源", value: "", type: "select", options: [{ label: "自制", value: "produce" }, { label: "采购", value: "purchase" }, { label: "外协", value: "out" }], itemRules: [{ required: true, trigger: "change" }], itemReadOnly: true },
      { prop: "productStatus", label: "产品状态", value: "enable", type: "select", options: [{ label: "启用", value: "enable" }, { label: "禁用", value: "disabled" }], itemRules: [{ required: true, trigger: "change" }] },
      // { prop: "approvalStatus", label: "审批状态", value: "", type: "select", options: [{ label: "审批中", value: "in_approval" }, { label: "审批通过", value: "approved" }, { label: "审批拒绝", value: "review_failed" }] },
      // { prop: "reasonRejection", label: "驳回理由", value: "", type: 'textarea', sm: 24 },
      // { prop: "approvalCompletionDate", label: "审批完成时间", value: "", type: 'date' },
      // { prop: "documentStatus", label: "单据状态", value: "", type: "select", options: [{ label: "草稿", value: "draft" }, { label: "提交", value: "submit" }] },
      // { prop: "submitDate", label: "提交时间", value: "", type: 'date' },
      { prop: "remark", label: "备注", value: "", type: 'textarea', sm: 24 },
    ],
  },
  {
    tabCode: "specialAttribute",
    tabName: "特殊属性",
    tabContent: [
      { prop: "minInventory", label: "最小库存", value: "", type: "input", itemReadOnly: true },
      { prop: "maxInventory", label: "最大库存", value: "", type: "input", itemReadOnly: true },
      { prop: "safeInventory", label: "安全库存", value: "", type: "input", itemReadOnly: true },
      // { prop: "taxRate", label: "税率", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }] },
      // { prop: "purchasePrice", label: "采购牌价(含税)", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }], readOndy: true },
      // { prop: "salePrice", label: "销售牌价(含税)", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }], readOndy: true },
      // { prop: "costPrice", label: "成本价格(含税)", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [20, 8] }), trigger: 'blur' }], readOndy: true },
      // { prop: "excludingTaxCostPrice", label: "成本价格（不含税）", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [20, 8] }), trigger: 'blur' }], readOndy: true },
      // { prop: "purchasingUnit", label: "采购单位", value: "", type: "input", },
      // { prop: "salesConversionCoefficient", label: "销售单位转换系数", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 6] }), trigger: 'blur' }, { validator: formValidate('positiveNumber'), trigger: "blur" }] },
      // { prop: "salesUnit", label: "销售单位", value: "", type: "input", },
      // { prop: "procurementConversionCoefficient", label: "采购单位转换系数", value: "1", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 6] }), trigger: 'blur' }], render: false },
      // { prop: "batchFlag", label: "是否采用批次管理", value: "", type: "select", options: [{ label: "采用", value: true }, { label: "不采用", value: false }] },
      // { prop: "outboundMethod", label: "出库方式", value: "no_control", type: "select", options: [{ label: "按批号大小顺序", value: "size_order" }, { label: "按批次先入先出", value: "first_in_first_out" }, { label: "按保质期", value: "quality_guarantee_period" }, { label: "不做控制", value: "no_control" }] },
      // { prop: "procurementLeadTimeDay", label: "采购提前期", value: "", type: "input", itemRules: [{ validator: formValidate('bigInt'), trigger: 'blur' }], itemSlot: { position: 'append', content: '(天)' } },
      // { prop: "procurementReturnFlag", label: "是否允许采购退货", value: "", type: "select", options: [{ label: "允许", value: true }, { label: "不允许", value: false }] },
      // { prop: "overchargeRatio", label: "允许超收比例", value: "1", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(%)' } },
      // { prop: "underpaymentRatio", label: "允许欠收比例", value: "1", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(%)' } },
      // { prop: "inspectFlag", label: "收货是否检验", value: "", type: "select", options: [{ label: "是", value: true }, { label: "否", value: false }] },
      { prop: "dailyConsumption", label: "日消耗量", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }] },
      { prop: "density", label: "密度", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [20, 6] }), trigger: 'blur' }], itemSlot: { position: 'append', content: '(kg/m³)' } },
      { prop: "acrossFlats", label: "对边", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }] },
      { prop: "externalDiameter", label: "外径", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }] },
      { prop: "wallThickness", label: "壁厚", value: "", type: "input", itemRules: [{ validator: formValidate({ type: 'decimal', params: [10, 2] }), trigger: 'blur' }] },
      { prop: "d", label: "D", value: "", type: 'input' },
      { prop: "d1", label: "D1", value: "", type: 'input' },
      { prop: "d2", label: "D2", value: "", type: 'input' },
      { prop: "d3", label: "D3", value: "", type: 'input' },
      { prop: "d4", label: "D4", value: "", type: 'input' },
      { prop: "i1", label: "I1", value: "", type: 'input' },
      { prop: "i2", label: "I2", value: "", type: 'input' },
      { prop: "i3", label: "I3", value: "", type: 'input' },
      { prop: "l", label: "L", value: "", type: 'input' },
      { prop: "l1", label: "L1", value: "", type: 'input' },
      { prop: "l2", label: "L2", value: "", type: 'input' },
      { prop: "l3", label: "L3", value: "", type: 'input' },
      { prop: "l4", label: "L4", value: "", type: 'input' },
      { prop: "l5", label: "L5", value: "", type: 'input' },
      { prop: "l6", label: "L6", value: "", type: 'input' },
      { prop: "l7", label: "L7", value: "", type: 'input' },
      { prop: "s", label: "S", value: "", type: 'input' },
      { prop: "formula", label: "公式", value: "", type: 'input' },
    ]
  }
]