export default {
  // 审批单类型
  approvalList: [
    { label: "b001", value: "SalesQuo" },
    { label: "b002", value: "fixPointPrice" },
    { label: "b003", value: "defectiveProductHandlingForm" },
    { label: "b004", value: "defectiveProductHandlingForm" },
    { label: "b005", value: "defectiveProductHandlingForm" },
    { label: "b006", value: "defectiveProductHandlingForm" },
    { label: "b007", value: "defectiveProductHandlingForm" },
    { label: "b008", value: "defectiveProductHandlingForm" },
    { label: "b009", value: "purchaseOrderForm" },
    { label: "b010", value: "outsourcingOrderForm" },
    { label: "b011", value: "outsourProcessForm" },
    { label: "b012", value: "purReconciliationForm" },
    { label: "b013", value: "salesReconForm" },
    { label: "b014", value: "outReconciliationForm" },
    { label: "b015", value: "buyingRequisitionForm" },
    { label: "b016", value: "orderChangesForm" },
    { label: "b017", value: "stopTicketForm" },
    { label: "b018", value: "productionBomForm" },
    { label: "b019", value: "excessiveNoticeForm" },
    { label: "b020", value: "repleNoticeForm" },
    { label: "b021", value: "saleAdjustForm" },
    { label: "转审", value: "transferForm" },
    { label: "b022", value: "defectiveProductHandlingForm" },
  ],
} 